### ISSUE TITLE
node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1 

### ISSUE THREAD

**Issue by breshman** [Aginix/nestjs-firebase-admin#191] opened 2020-07-18 16:45 UTC
`[11:44:13] Starting compilation in watch mode...

node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: DocumentData, UpdateData, Firestore, GeoPoint, Transaction, WriteBatch, WriteResult, DocumentReference, DocumentSnapshot, QueryDocumentSnapshot, OrderByDirection, WhereFilterOp, Query, QuerySnapshot, DocumentChangeType, CollectionReference, FieldValue, FieldPath, Timestamp, v1beta1, v1, OK, CANCELLED, UNKNOWN, INVALID_ARGUMENT, DEADLINE_EXCEEDED, NOT_FOUND, ALREADY_EXISTS, PERMISSION_DENIED, RESOURCE_EXHAUSTED, FAILED_PRECONDITION, ABORTED, OUT_OF_RANGE, UNIMPLEMENTED, INTERNAL, UNAVAILABLE, DATA_LOSS, UNAUTHENTICATED, FirebaseFirestore

23 declare namespace FirebaseFirestore {
   ~~~~~~~

  node_modules/firebase-admin/node_modules/@google-cloud/firestore/types/firestore.d.ts:25:1
    25 declare namespace FirebaseFirestore {
       ~~~~~~~
    Conflicts are in this file.

node_modules/firebase-admin/node_modules/@google-cloud/firestore/types/firestore.d.ts:25:1 - error TS6200: 
Definitions of the following identifiers conflict with those in another file: DocumentData, UpdateData, Firestore, GeoPoint, Transaction, WriteBatch, WriteResult, DocumentReference, DocumentSnapshot, QueryDocumentSnapshot, OrderByDirection, WhereFilterOp, Query, QuerySnapshot, DocumentChangeType, CollectionReference, FieldValue, FieldPath, Timestamp, v1beta1, v1, OK, CANCELLED, UNKNOWN, INVALID_ARGUMENT, DEADLINE_EXCEEDED, NOT_FOUND, ALREADY_EXISTS, PERMISSION_DENIED, RESOURCE_EXHAUSTED, FAILED_PRECONDITION, ABORTED, OUT_OF_RANGE, UNIMPLEMENTED, INTERNAL, UNAVAILABLE, DATA_LOSS, UNAUTHENTICATED, FirebaseFirestore

25 declare namespace FirebaseFirestore {
   ~~~~~~~

  node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1
    23 declare namespace FirebaseFirestore {
       ~~~~~~~
    Conflicts are in this file.

node_modules/firebase-admin/node_modules/@google-cloud/firestore/types/firestore.d.ts:168:5 - error TS2374: Duplicate string index signature.

168     [key: string]: any; // Accept other properties, such as GRPC settings.
        ~~~~~~~~~~~~~~~~~~~

[11:44:19] Found 3 errors. Watching for file changes.
`

**Comment by ItayElgazar** [comment] 2020-07-28 19:26
any news on that?

**Comment by n3n** [comment] 2020-07-29 05:03
@breshman @ItayElgazar I didn't face this issue, however you can try `v1.1.1` this version updated dependencies version. Please let me know if it works or not.

**Comment by CodingAleCR** [comment] 2020-08-16 21:52
That is the version I am trying to use and the one that ends with this issue, maybe it is because of using an updated version of firebase-admin. I would suggest a compatibility table.

**Comment by CodingAleCR** [comment] 2020-08-17 17:56
The issue is because of outdated dependencies, however, the latest Firebase Admin SDK is missing export for one of the Remote Config classes, and updating `firebase-admin` libraries won't work. I've submitted a fix for `firebase-admin` [here](https://github.com/firebase/firebase-admin-node/pull/996), so when that gets merged I'll submit a PR here for updating the dependencies and also suggesting a compatibility chart.

**Comment by n3n** [comment] 2020-08-20 04:38
The issue has been fixed in `v2.0.0`, that supports `firebase-admin v9.xx`.

**Comment by CodingAleCR** [comment] 2020-08-20 04:48
Nice! I saw you used the lib modules instead of the exposed one, might be a good idea to use a single one when they fix their mistake, though it might take a while. Anyways, thank you very much!

**Comment by CodingAleCR** [comment] 2020-08-20 21:59
I just got noted that firebase admin 9.1.1 is out with the small fix on imports, if it's something worth making a patch release about. Kudos!

**Closed** 2020-09-07 08:15 UTC
